apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sr-argo-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/narendra7306/argocd-demo.git
    targetRevision: 1.1.10
    path: yamls
  destination:
    server: https://kubernetes.default.svc
    namespace: sr-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
