apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: sr
namePrefix: dev-
namespace: sr-ns
commonLabels:
  env: poc
resources:
  - configmap.yaml
  - cron-job.yaml
  - job.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - pv.yaml
  - pvc.yaml
  - secret.yaml
