apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: javaApp
namePrefix: cd-
namespace: jenkins-cd
commonLabels:
  jenkins: cd
resources:
    
  - yamls/deployment.yaml
  - yamls/service.yaml
  
