apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
  namespace: jenkins-cd
  labels:
    jenkins: cd
spec:
  type: NodePort
  selector:
    jenkins: cd
  ports:  
    - port: 5000
      targetPort: 80
      nodePort: 32000
