apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deploy
  namespace: jenkins-cd
  labels:
    jenkins: cd
spec:
  replicas: 2
  selector:
    matchLabels:
      jenkins: cd
  template:
    metadata:
      labels:
        jenkins: cd
    spec:
      imagePullSecrets:
        - name: cd-secret
      containers:
      - name: java-c1
        image: zentech.jfrog.io/docker/java-app:32
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 600; done;"]
        ports:
        - containerPort: 8080
